export enum ICON_NAMES {
  alignCenter = 'align-center',
  alignLeft = 'align-left',
  alignRight = 'align-right',
  backLayer = 'back-layer',
  brush = 'brush',
  chevronDown = 'chevron-down',
  chevronUp = 'chevron-up',
  circle = 'circle',
  exclamationCircle = 'exclamation-circle',
  frontLayer = 'front-layer',
  pencil = 'pencil',
  photograph = 'photograph',
  plus = 'plus',
  rectangle = 'rectangle',
  redo = 'redo',
  shapes = 'shapes',
  spray = 'spray',
  textBold = 'text-bold',
  text = 'text',
  textItalic = 'text-italic',
  trash = 'trash',
  triangle = 'triangle',
  undo = 'undo',
  zoomPlus = 'zoom-plus',
  zoomMinus = 'zoom-minus',
}
